name: Deploy Pages

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

permissions:
  contents: write

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用该时区时间）

jobs:
  deploy-github-pages:
    name: 开始部署
    runs-on: ubuntu-latest

    steps:
      - name: 检出源码
        uses: actions/checkout@v3
      - name: 安装 PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: 安装 Node 环境
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - name: 安装依赖
        run: pnpm i --frozen-lockfile
      - name: 打包
        run: pnpm build
      - name: 部署 GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: pages
          FOLDER: docs/.vitepress/dist
